<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Aduan Form</title>
</head>
<body>

    <?php
        echo $this->getContent();
    ?>

    <h2>Buat Aduan</h2>

    <?php echo $this->tag->form(array("aduan/save",'enctype'=> "multipart/form-data")); ?>

        <p>
            <label for="judul">judul</label>
            <?php echo $this->tag->textField("judul"); ?>
        </p>

        <p>
            <label for="isi">isi</label>
            <?php echo $this->tag->textField("isi"); ?>
        </p>

        <p>
            <label for="isi">gambar</label>
            <?php echo $this->tag->fileField("gambar"); ?>
        </p>

        <p>
            <?php echo $this->tag->submitButton("buat"); ?>
        </p>

    </form>

</body>
</html>

